### ISSUE TITLE
error fetching aniMotum or ggmagnify from github

### ISSUE THREAD

**Issue by HVinther** [ropensci/rix#159]
I get an error similar to #156 when trying to pull {aniMotum} or {ggmagnify} from github, as seen in code snippet below. I haven't been able to identify any dependencies not listed on cran. 

I've tried a few different commits for both with similar results.

```{R}
library(rix)

rix(r_ver = "latest",
    r_pkgs = NULL,
    system_pkgs = NULL,
    git_pkgs = list(
      list(
        package_name = "aniMotum",
        repo_url = "https://github.com/ianjonsen/aniMotum/",
        branch_name = "master",
        commit = "00d1c778c6cae78c46c1c5a4016512ea44654565"
      ),
      list(
        package_name = "ggmagnify",
        repo_url = "https://github.com/hughjonesd/ggmagnify/",
        branch_name = "master",
        commit = "602d42d150a0b1e0895c36b9c6c8c2f56402e116"
      )
    ),
    ide = "rstudio",
    overwrite = TRUE,
    print = TRUE)

```

The packages did succesfully install using `remotes::install_github`.

**Comment by b-rodrigues** [comment]
Thanks, I can replicate this problem, also using curl:

```
curl -X GET "http://git2nixsha.dev:1506/hash?repo_url=https://github.com/hughjonesd/ggmagnify/&branchName=master&commit=602d42d150a0b1e0895c36b9c6c8c2f56402e116" -H "accept: */*"
```

```
{"error":"500 - Internal server error"}
```

I will continue investigating.

**Comment by b-rodrigues** [comment]
So I fear this is going to be tricky: running the code locally produces the output, but somehow something seems to error when going through plumber. I even updated the whole environment on the server, but it still fails for ggmagnify.

**Comment by b-rodrigues** [comment]
@HVinther could you try with latest master? You can now remove the 'branchName':

```
library(rix)

rix(r_ver = "latest",
    r_pkgs = NULL,
    system_pkgs = NULL,
    git_pkgs = list(
      list(
        package_name = "aniMotum",
        repo_url = "https://github.com/ianjonsen/aniMotum/",
        commit = "00d1c778c6cae78c46c1c5a4016512ea44654565"
      ),
      list(
        package_name = "ggmagnify",
        repo_url = "https://github.com/hughjonesd/ggmagnify/",
        commit = "602d42d150a0b1e0895c36b9c6c8c2f56402e116"
      )
    ),
    ide = "rstudio",
    overwrite = FALSE,
    print = TRUE)
```

**Comment by HVinther** [comment]
I get the following error message, when using the latest version.

Fejl: Request `curl::curl_fetch_memory(url = 'https://api.github.com/repos/NixOS/nixpkgs/commits?sha=nixpkgs-unstable')` failed:
 Timeout was reached: [api.github.com] Resolving timed out after 10001 milliseconds

**Comment by b-rodrigues** [comment]
That seems unrelated, could you try with setting `rix(r_ver = "4.3.1")` to avoid looking for the latest rix commit and try again?

**Comment by b-rodrigues** [comment]
Somehow it seems you can't do api GETs? try first

`options(rix.sri_hash="api_server")`

and then try again

**Comment by HVinther** [comment]
Setting the option I get the error message, when rerunning the rix command:
Fejl: Request `curl::curl_fetch_memory(url = 'http://git2nixsha.dev:1506/hash?repo_url=https://github.com/ianjonsen/aniMotum/&commit=00d1c778c6cae78c46c1c5a4016512ea44654565')` failed:
 Timeout was reached: [git2nixsha.dev:1506] Resolving timed out after 10001 milliseconds
If it's a Github repo, check the url and commit.
Are these correct? If it's an archived CRAN package, check the name
of the package and the version number.

I tried curl::curl_fetch_memory("https://zed.dev/install.sh") to test if the curl package worked at all. This returned status code 200 along with data.

**Comment by b-rodrigues** [comment]
very weird, I don't get timeouts on my side

**Comment by HVinther** [comment]
If I call `curl "https://api.github.com/repos/NixOS/nixpkgs/commits?sha=nixpkgs-unstable"` from the terminal

**Comment by philipp-baumann** [comment]
> If I call `curl "https://api.github.com/repos/NixOS/nixpkgs/commits?sha=nixpkgs-unstable"` from the terminal I get no timeout, but recieve the data from url. The timeout error when callin `curl::curl_fetch_memory(url = 'https://api.github.com/repos/NixOS/nixpkgs/commits?sha=nixpkgs-unstable')` in R seems to persist however. 

Thanks for your diagnostics. That is a hint for us to work on a fix I think.

**Comment by b-rodrigues** [comment]
@HVinther could you try again from latest master? The api is being served from Port 443 now

**Comment by HVinther** [comment]
> @HVinther could you try with latest master? You can now remove the 'branchName':
> 
> ```
> library(rix)
> 
> rix(r_ver = "latest",
>     r_pkgs = NULL,
>     system_pkgs = NULL,
>     git_pkgs = list(
>       list(
>         package_name = "aniMotum",
>         repo_url = "https://github.com/ianjonsen/aniMotum/",
>         commit = "00d1c778c6cae78c46c1c5a4016512ea44654565"
>       ),
>       list(
>         package_name = "ggmagnify",
>         repo_url = "https://github.com/hughjonesd/ggmagnify/",
>         commit = "602d42d150a0b1e0895c36b9c6c8c2f56402e116"
>       )
>     ),
>     ide = "rstudio",
>     overwrite = FALSE,
>     print = TRUE)
> ```

I just used `{remotes}` to reinstall `{rix}`  and ran snippet above. I did not get any errors from rix, but when the packages failed to build, with the following the error:

```
exporting https://github.com/ianjonsen/aniMotum/ (rev 00d1c778c6cae78c46c1c5a4016512ea44654565) into /nix/store/94nab683is7b96nh6m76r3a4723kc0jr-aniMotum-00d1c77
Initialized empty Git repository in /nix/store/94nab683is7b96nh6m76r3a4723kc0jr-aniMotum-00d1c77/.git/
fatal: unable to access 'https://github.com/ianjonsen/aniMotum/': OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme
fatal: unable to access 'https://github.com/ianjonsen/aniMotum/': OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme
fatal: unable to access 'https://github.com/ianjonsen/aniMotum/': OpenSSL/3.0.14: error:16000069:STORE routines::unregistered scheme
Unable to checkout 00d1c778c6cae78c46c1c5a4016512ea44654565 from https://github.com/ianjonsen/aniMotum/.
error: builder for '/nix/store/8afld8myc9dq40w1rfnnciiksrjjwl2n-aniMotum-00d1c77.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/bk3r9b77vf1f49prj7c61a5q60d14c18-r-aniMotum.drv' failed to build
error: build of '/nix/store/3g91fxvpsrws1z12hndlg062pqrffq53-R-4.4.1.drv', '/nix/store/bk3r9b77vf1f49prj7c61a5q60d14c18-r-aniMotum.drv', '/nix/store/sbxnap725qcfsjgp21vjd1h6qpgi6gwj-stdenv-linux.drv', '/nix/store/wl4anq2wd7jr6h0q0ql0axjaflky1rq6-r-ggmagnify.drv' failed
```
Changing the R-version from "latest" to "4.4.0"  gave a successful build.

Note: When I made the issue I think I use Fedora with cran2copr. I've since switched to openSUSE Tumbleweed using the open build service mirror of Cran.

**Comment by b-rodrigues** [comment]
Thanks! Interesting that changing the R version works, there might be something that interferes with the packages in the latest nixpkgs master. I'll investigate and, I'll close this thread in the meantime as I think the original problem is solved.

Thanks again for testing!
