### ISSUE TITLE
use pre-commit.ci lite bot for applying code fixes like linting

### ISSUE THREAD

**Issue by philipp-baumann** [ropensci/rix#265]
I'd propose to use the pre-commit.ci lite bot to apply styling/linting. The main advantage it does auto-fixing when needed. https://pre-commit.ci/lite

So this would apply styling automatically. It could deal with cases like this as well: https://github.com/b-rodrigues/rix/pull/257
Here is an example setup I implemented for one of my packages a while ago, here is action for applying to a PR branch.

https://github.com/spectral-cockpit/opusreader2/pull/91/commits/abe3edc3933f63dd871e0565bca6c030a6077a1d

What we would need to do is 1) authorize the bot on the repo, 2) define something like here but with newer version tags maybe: https://github.com/spectral-cockpit/opusreader2/blob/main/.github/workflows/code-check.yml 3) add a minimal pre-commit config and add `style-files` hook (https://cran.r-project.org/web/packages/precommit/vignettes/available-hooks.html) i have used a bit a more extensive setup but to illustrate https://github.com/spectral-cockpit/opusreader2/blob/main/.pre-commit-config.yaml

**Comment by b-rodrigues** [comment]
So we could replace the current styler action? Styler does the fixing as well, and as it's currently configured, it opens a PR. I don't mind changing, but what would be the advantage over what we have now?

**Comment by philipp-baumann** [comment]
> So we could replace the current styler action? Styler does the fixing as well, and as it's currently configured, it opens a PR. I don't mind changing, but what would be the advantage over what we have now? Fixing for PRs as well?

like discussed on matrix. The advantage i see is auto-fixing directly in the PR and a green lint CI in PRs. Priority is not super high. I could do a minimal setup if i find a little bit of time.

**Comment by philipp-baumann** [comment]
closing, as lessons learnt, see in PR comments https://github.com/ropensci/rix/pull/295
