### ISSUE TITLE
`nix_build()` does not remove running `nix-build` process when exiting via ctrl+c

### ISSUE THREAD

**Issue by philipp-baumann** [ropensci/rix#304]
-  After creating a Nix expression that builds, `nix_build()` sys wrapper does not stop the running `nix-build` command when exiting in R via ctrl+c.

**Comment by philipp-baumann** [comment]
@b-rodrigues its very strange, i found running background processes on on macOS and also Ubuntu, although we have a `on.exit()` hook. do you have any idea. Can you also interactively test on a rather long new expression that is not yet in your cache?

https://github.com/ropensci/rix/blob/1783f724bec5e9381f1cec0e6c744613616eda81/R/nix_build.R#L115-L120

**Comment by b-rodrigues** [comment]
from my reading of https://bugs.r-project.org/show_bug.cgi?id=18087

seems to be intended behavior ?

**Comment by philipp-baumann** [comment]
its SIGINT (exiting via ctrl+c or ESC) in this case. However, apart from some low-level control via the C API, on.exit , withCallingHandler and tryCatch etc. do not really work well to clean up background processes properly. 

Interestingly, {sys} seems to sent a SIGINT to the process, but this seems to only happen on macOS.

**Comment by philipp-baumann** [comment]
addressed with #307
