### ISSUE TITLE
Rhub workflow now failing

### ISSUE THREAD

**Issue by b-rodrigues** [ropensci/rix#305]
https://github.com/ropensci/rix/actions/workflows/rhub.yaml

could it be because of the linter?

**Comment by philipp-baumann** [comment]
> https://github.com/ropensci/rix/actions/workflows/rhub.yaml
> 
> could it be because of the linter?

hmm indirectly. I think i adjusted the line length, to please lintr, in the code that boileplates custom `.Rprofile`. 
![Uploading rix-update-after-linting.JPG…]()
