### ISSUE TITLE
Creating the connection creates an empty file

### ISSUE THREAD

**Issue by b-rodrigues** [ropensci/rix#341]
https://github.com/ropensci/rix/blob/0b8a31de10ee54a2ed06ca99b9f0efc126a6a2fc/R/rix_init.R#L142

Because creating a connection creates an empty .Rprofile, the action "create_missing" fails to write a file, since an .Rprofile is there already, even if empty. So nothing happens.

**Comment by philipp-baumann** [comment]
Thanks @b-rodrigues #342
