### ISSUE TITLE
renv2nix issues

### ISSUE THREAD

**Issue by mihem** [ropensci/rix#368]
@b-rodrigues Thanks for renv2nix. As i said I think this is super useful so I was excited to test this new feature.

This is more a collection of problems/ideas than a formal bug report.

I think there should be a renv2nix vignette, which give concrete examples. The function help is extensive, but misses examples and often vignettes are easier as a start.

Is the workflow: You open R in the renv environment and call `renv2nix(project_path = ".")` or should you be outside of the renv enviroment or is this irrelevant?

When i tried it on a toy project it worked fine, although i got the warning message: 

```
### .Rprofile file already exists. You may want to call rix_init(rprofile_action = 'append') manually to ensure correct functioning of your Nix environment. ###
```

Since `renv` projects always have a `.Rprofile` i found this confusing, shouldn't renv2nix then not just do that? What is the problem if this is not done?

When I tried `revn2nix` on my real project, I got the following warning message (I use Visual Studio Code):

```
## .Rprofile file already exists. You may want to call rix_init(rprofile_action = 'append') manually to ensure correct functioning of your Nix environment. ###


cannot open the connectionwarning messages from top-level task callback 'vsc.workspace'
Warning message:
In file(con, "w") :
  cannot open file '/tmp/RtmppLc1a1/vscode-R/workspace.json': No such file or directory
```

What does this vsc. workspace connection problem mean?

However, the main problem was that `nix-build` failed with:

```
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/4wr1ahk4xsis4vf2yy0gcygivc5l6l7x-source/pkgs/stdenv/generic/make-derivation.nix:300:7

       … while evaluating attribute 'buildInputs' of derivation 'nix-shell'
         at /nix/store/4wr1ahk4xsis4vf2yy0gcygivc5l6l7x-source/pkgs/stdenv/generic/make-derivation.nix:347:7:
          346|       depsHostHost                = lib.elemAt (lib.elemAt dependencies 1) 0;
          347|       buildInputs                 = lib.elemAt (lib.elemAt dependencies 1) 1;
             |       ^
          348|       depsTargetTarget            = lib.elemAt (lib.elemAt dependencies 2) 0;

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'datathin' missing
       at /home/mischko/Documents/beruf/forschung/ml_izkf/default.nix:720:11:
          719|           abind
          720|           datathin
             |           ^
          721|           mclust

```

The corresponding lines in default.nix:

```
  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "CSFAtlasTools";
      src = pkgs.fetchgit {
        url = "https://github.com/mihem/CSFAtlasTools";
        rev = "02d485896d383e2a876f0f3bbae7265c017e7e92";
        sha256 = "sha256-q9qBYrGrn96lG5I9xUuWCLw0CSnh7BA5Qs9AAcRtz0E=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          dplyr
          glue
          readr
          ggplot2
          tidyr
          RColorBrewer
          bestNormalize
          pheatmap
          recipes
          tibble
          viridis
          broom
          WRS2
          Seurat
          abind
          datathin
          mclust
          tune
          yardstick
          ggsignif;
      };
    })


    (pkgs.rPackages.buildRPackage {
      name = "datathin";
      src = pkgs.fetchgit {
        url = "https://github.com/anna-neufeld/datathin";
        rev = "58eb154609365fa7301ea0fa397fbf04dd8c28ed";
        sha256 = "sha256-rtRpwFI+JggX8SwnfH4SPDaMPK2yLhJFTgzvWT+Zll4=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          VGAM
          knitr
          extraDistr
          mvtnorm;
      };
    })
   ];
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ git_archive_pkgs rpkgs  system_packages   ];
  
}
```

So datathin is not found, but required by CSFAtlasTools (personal package). But there is actually datathin with correct github repo url and rev (why is the commit ID called "RemoteSha" in renv.lock called "rev" here?). So is the problem just the order?

Thanks!

**Comment by mihem** [comment]
@b-rodrigues 
Thanks for you quick response.

> No, ideally, you should copy the renv.lock file into a new folder, and call renv2nix() there. This is to avoid the issues you had with the .Rprofile file. Both {renv} and {rix} rely on project-level .Rprofile files to correctly set up projects, so if you use the same folder for both, you will have issues.

This makes sense and solves the warning.


> But renv2nix() then detects that {datathin} comes from github and correctly includes the right code to install it from Github. But still, from the point of view of {CSFAtlasTools}, {datathin} is being included as a dependency that should come from CRAN. This issue is described here: https://docs.ropensci.org/rix/articles/z-advanced-topic-handling-packages-with-remote-dependencies.html
You should rewrite the expression a little (as described in the vignette) to make it work. For now, {rix} doesn’t handle remote dependencies automatically, and I don’t know if it ever will. It is not an easy issue to solve.

Okay. Although you wrote it quite verbosely in the vignette, I still find it hard to understand what to change. The git part of my `default.nix` looks like this:

```
But renv2nix() then detects that {datathin} comes from github and correctly includes the right code to install it from Github. But still, from the point of view of {CSFAtlasTools}, {datathin} is being included as a dependency that should come from CRAN. This issue is described here: https://docs.ropensci.org/rix/articles/z-advanced-topic-handling-packages-with-remote-dependencies.html

You should rewrite the expression a little (as described in the vignette) to make it work. For now, {rix} doesn’t handle remote dependencies automatically, and I don’t know if it ever will. It is not an easy issue to solve.
```


Can you help me, how to change to make this work?

I would agree with your conclusion that this is tedious. So i think it seems as something which should be handled by rix.
I wouldn't agree with the three reasons, why rix should handle this:
1-2 : It may be a common situation if you use mature packages. But if you use experimental projects this may happend. This is especially true if you create a package for the functions of your analysis (which may rely on packages that are not on CRAN, actually a quite common situation in my field and many of those packages unfortunately never make it to CRAN e..g datathin or https://github.com/bnprks/BPCells )
3: If there is renv.lock the user already decided, which commit should be used.

**Comment by b-rodrigues** [comment]
could you post the default.nix in a gist and post the link here? I'll help you with it

I will rethink this handling of remote dependencies

**Comment by mihem** [comment]
thanks

https://gist.github.com/mihem/d23dacdd3cd0015a9e0ae4e971c8cc6d

**Comment by b-rodrigues** [comment]
Here is the correct default.nix: https://gist.github.com/mihem/d23dacdd3cd0015a9e0ae4e971c8cc6d?permalink_comment_id=5294035#gistcomment-5294035

search for all instances of `datathin` to see how it is used. Also, your example was really great, because it included a relatively old version of R, but much more recent packages, which lead to an issue with `{unigd}`. I’ll try to add some sort of warning if `renv2nix()` detects packages that are more recent than the version of R included in the `renv.lock` file.

**Comment by mihem** [comment]
@b-rodrigues thanks, with your changes, nix-build runs successful.

Glad that it was a useful example for you.
Actually in my workflow this is common scenario.

I start the analysis, which may take several months or even years and submit the paper.
In the revision , I want to add further analysis on top. And this may involve packages that were not even released at the time when I started the analyses.

But I am worried (especially after reading your book) that upgrading to a newer R version could change my exisitng analysis, which i want to avoid. So I would prefer to keep R version 4.3.1

I checked a few version between `renv.lock` and `nix-shell` and noticed further differences.
e.g.
`Bioconductor` is `3.18` in the `renv.lock` but `3.19` in the nix shell. This is dependent on the R version, so the issue above. But I think all Bioconductor packages are dependedn on this version, so this really increases chanced that my analysis might fail or might lead to different results?
or `RcppArmadillo` version `0.12.8.2.1` in `renv.lock`, but `0.12.8.4.0` in `nix-shell`.

**Comment by b-rodrigues** [comment]
The version differences between the renv.lock file and the default.nix is all due to how renv and Nix manage versions. For minor releases like going from package xyz 1.0.0 to xyz 1.0.1 this shouldn't matter much. But you're right different versions *could* lead to different results.

My advice: only use renv2nix to convert old projects not to start new ones. Then, verify that the results are not impacted by switching from renv.lock to default.nix. In the vast majority of cases you should be fine.

For new projects, start with a fresh default.nix and commit it to version control. Should you need to update R version and packages, it's only a matter of re-running rix() with a fresher R version. Should anything break, just revert to the previous commit.

**Comment by mihem** [comment]
Thanks.
Another topic I would be interested in and that you might want to include in the vignette.
How would you combine docker and renv2rix .

In the vignette you copy the generate_env.R, which calls rix, so here renv2rix. but here you manually had to change the resulting default.nix because of the remote dependency issue (which is of course true also without renv2rix) so not suitable for a dockerfile.  How would you do that?

**Comment by b-rodrigues** [comment]
For now you'd have to create and fix the default.nix file outside of the docker image build process and copy that to the image

**Comment by mihem** [comment]
Thanks.
I think this is another argument for automatic handling of remote dependencies. Then the user would just have to provide `renv.lock` and everything else happens automatically.

I tested the docker solution and the docker building worked very smoothly.
I used your docker template, but copied `default.nix` and `.Rprofile` instead of ``generate_renv.R`

A major advantage was that is was much faster. Took me around 5 mins to build while the solution using `renv::restore()` took around 1h plus I needed several attempts to include all relevant packages.

However, when I then run the container it took very long to run `nix-shell`. In contrast, this only takes a few seconds in my local non-Docker environment.
I changed the Dockerfile to `RUN nix-shell` instead of `CMD nix-shell`. Executing RUN -nix-shell took around 8 minutes. The advantage is that when I then run the docker `nix-shell` takes a few seconds.
Here's a gist if you want to test for yourself
https://gist.github.com/mihem/549cdc6bc0877c8e2f91a8a97765c062

Do you know why it takes so long to run `nix-shell` in the docker environment? On the other hand rix is still significantly faster than renv alone (~12min vs ~60 min in my case on my machine). On the other hand it's larger (3.41 GB vs 4.43 GB).

**Comment by b-rodrigues** [comment]
That's very interesting thanks! It's very surprising it takes so long to run nix-shell in my tests it's only a matter of seconds. How about RUN nix-build, then RUN nix-shell then CMD nix-shell? would this result in faster execute times?

**Comment by mihem** [comment]
Thanks for your quick response.

Maybe that's because there are so many packages in this docker image? Can you test my gist (https://gist.github.com/mihem/549cdc6bc0877c8e2f91a8a97765c062
)? (using your corrected default.nix from earlier https://gist.github.com/mihem/d23dacdd3cd0015a9e0ae4e971c8cc6d?permalink_comment_id=5294035#gistcomment-5294035)

Yeah, that's why i changed it do `RUN nix-shell` .. but this take ~ 8 min on my machine, while the rest of the docker building only took ~5min. And when i then run the docker interactively and run`nix-shell` again it's a matter of seconds. So that would be a okay-ish solution. But of course best solution would be if `RUN nix-shell` would also be fast, because then re-building docker  image (maybe because I added a package) would be 5 min using rix instead of 60 min using renv only.

**Comment by mihem** [comment]
@b-rodrigues sorry, could you reproduce this slow `nix-shell` ?

**Comment by mihem** [comment]
closed in favor of https://github.com/ropensci/rix/issues/370 because it's not `renv2nix` related.
