### ISSUE TITLE
Roadmap: first CRAN release

### ISSUE THREAD

**Issue by philipp-baumann** [ropensci/rix#77]
As discussed on matrix, here is our progress list for our planned CRAN release.

- [x] Finalize vignette collection
- [x] Implement `rix::with_nix()`

Then, ready to go!

**Comment by b-rodrigues** [comment]
All that's missing now is re-reading the vignettes, and I think we're good. We'll have to discuss if we do a submission to r open sci or not

**Comment by b-rodrigues** [comment]
We're practically done. Last thing to implement: compute the hash of github or cran archive packages locally if nix is available.
